# port for scalarm node manager web server
port: 12200
# login and password to access this manager
login: eusas
password: hidden
# address to the information service
scalarm_information_service_url: localhost:11200
# login and password to access the information service
information_service_login: eusas
information_service_password: hidden
# where Scalarm Node Manager will unpack managers
installation_dir: /opt
# from which port installed managers will be started
starting_port: 3001
# time interval between subsequent registration of node manager
registration_interval: 300

# Monitoring section
# url to the mongo db server
monitoring_db_url: localhost:10000
# table name within the server
monitoring_db_name: eusas_monitoring
monitoring_db_user: eusas
monitoring_db_pass: hidden
monitoring_interval: 30
# which metric should be monitored
# this is a list of names separeted with the ":" sign
# currently the following list is supported
monitored_metrics: cpu:memory:storage:experiment_manager
